### ISSUE TITLE
Does this package work with .net framework 3.5?

### ISSUE THREAD

**Issue by li-zhixin** [jeffkl/ManagedDism#106]
I'm a newbie to Dism, and I'm happy to see a library that makes it easy for me to do windows updates. But I need to adapt to Windows 7 without any updates installed, so I can rely on the .net framework version 3.5.

The current nuget package is not compatible with .net framework 3.5, do you think the adaptation work is more challenging, if not too many problems, I will send a pull request about this issue.

**Comment by jeffkl** [comment]
I'm not sure, you can certainly try compiling it against .NET 3.5.  As long as I'm not using any APIs that didn't ship until .NET Framework 4 it should work.
