### ISSUE TITLE
Clarification on need for ADK

### ISSUE THREAD

**Issue by cedws** [jeffkl/ManagedDism#107]
[This](https://github.com/jeffkl/ManagedDism/wiki) wiki page says that the ADK is required at runtime for this library to work under Windows 8, if I'm reading it correctly. But I'm on Windows 20H2 and able to run a test program without the ADK. I guess this makes sense because there's already a `DismApi.dll` in `System32`.

Is the ADK still needed on Windows 10?

**Comment by Shidell** [comment]
DISM is built-in to Windows 10, although (depending on your needs and/or scenario), you may need a newer version of ADK than what's already available in your version of Windows 10. If you keep Windows 10 up-to-date based on Microsoft's release schedule, you should always be on the latest—but, for example, if you're part of an organization that manages patches and is back some number of releases, then you might need to investigate updated ADK means.

**Comment by cedws** [comment]
Thanks, understood. This info verbatim would be a good addition to the page.
As a consumer of this library, what can I expect to see if the version of DISM is too outdated for the way it's being used?
