### ISSUE TITLE
How to check whether a feature is enabled or not?

### ISSUE THREAD

**Issue by mat007** [jeffkl/ManagedDism#156]
Hi,

Using [GetFeatures](https://github.com/jeffkl/ManagedDism/blob/main/src/Microsoft.Dism/DismApi.GetFeatures.cs#L54) we can retrieve a list of all features, the documentation says «regardless of whether the features are enabled or disabled».
However I’m not sure how to know if a feature is enabled or disabled.

The features have a State field of type [DismPackageFeatureState](https://github.com/jeffkl/ManagedDism/blob/main/src/Microsoft.Dism/NativeEnums.cs#L225), but enabled is not among the possible values (only installed, …).

How do I query whether a feature is enabled or disabled?

Thanks!

**Comment by jeffkl** [comment]
This managed API is just a wrapper around the native API.  The documentation for DismGetFeatures does say it will return all features whether or not they are enabled:

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dismgetfeatures-function?view=windows-11

Then each feature has a property indicating its state:

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism/dismpackagefeaturestate-enumeration?view=windows-11#constants

I would guess `NotPresent` is the indicator of it being disabled?

https://github.com/jeffkl/ManagedDism/blob/7f0bdaf95eca97af285bfcc286c841d17e3c84e7/src/Microsoft.Dism/NativeEnums.cs#L230

Do you see features with the state of `NotPresent` ?

**Comment by mat007** [comment]
Thanks for your answer @jeffkl 

Most of my features are either `Installed` or `Staged`, a few of them (like 2) are `NotPresent`.
When I cross check with `Dism` from the PS command line, it seems `Installed` maps to `Enabled`, and the other two to `Disabled`, e.g. 

![image](https://user-images.githubusercontent.com/2386884/159255176-10824e62-002b-40e8-8816-a11ab77f8a73.png)

```
PS C:\Users\Mathieu> Dism /online /Get-FeatureInfo /FeatureName:MSMQ-Server

Deployment Image Servicing and Management tool
Version: 10.0.22000.1

Image Version: 10.0.22000.588

Feature Information:

Feature Name : MSMQ-Server
Display Name : Microsoft Message Queue (MSMQ) Server Core
Description : This feature installs the core components of MSMQ which enables you to perform basic Message queuing functions. This feature is a minimum requirement.
Restart Required : Possible
State : Disabled
```

So, I suppose everything but `Installed` probably means `Disabled`.

Thanks!
