### ISSUE TITLE
.NET Standard 2.0 Support

### ISSUE THREAD

**Issue by wspait** [jeffkl/ManagedDism#73]
@jeffkl,

First, I would like to thank you and the contributors of this project for developing a solution for calling DISM without having to shell out to an external process. We have gotten great usage out of the managed WIM library as well.

I noticed that the latest version of this library only targets .NET Framework. The latest version of the WIM library was recently published to target both .NET Framework and .NET Standard 2.0.

Will this library also be republished to target .NET Standard 2.0? Being able to leverage this library for some of our .NET Core 2.1+ projects would be be of a great benefit to our team.

Thanks!

**Comment by jeffkl** [comment]
This is done available here: https://www.nuget.org/packages/Microsoft.Dism/2.0.14
