### ISSUE TITLE
Support for _DismApplyFfuImage

### ISSUE THREAD

**Issue by tester962** [jeffkl/ManagedDism#79]
_DismApplyFfuImage is an undocumented API function that applies a FFU image to a physical drive.
I've tried to find the function signature, but without much success.

I've got this from IDA:
```
__int64 __fastcall DismApplyFfuImage(const unsigned __int16 *a1, const unsigned __int16 *a2, struct CWindowsEvent *a3, void (__stdcall *a4)(unsigned int, unsigned int, void *))
{
  void *v5; // [rsp+20h] [rbp-18h]

  return DismApplyFfuImageInternal(a1, a2, a3, a4, v5);
}
```
The first two arguments seem to be of type string (perhaps the image path and the `\\.\PhysicalDriveX `drive), the 3rd argument is a CWindowsEvent struct (???) and the 4th one seems to be a DismProgressCallback.

Some help?

**Comment by jeffkl** [comment]
I was able to find this:

```
HRESULT WINAPI
  _DismApplyFfuImage(
    _In_ PCWSTR ImagePath,
    _In_ PCWSTR ApplyPath,
    _In_ PCWSTR PartPath);

HRESULT WINAPI
  _DismSplitFfuImage(
    _In_ PCWSTR ImagePath,
    _In_ PCWSTR PartPath,
    _In_ ULONGLONG PartSize);
```

I'll add both and get the usage from `dism.exe /Apply-Ffu` and `dism.exe /Split-Ffu` respectively.

**Comment by tester962** [comment]
Thanks. Is there any way to retrieve the progress without the callback?

**Comment by jeffkl** [comment]
It looks like only the `DismApplyFfuImageInternal` function takes a callback.  The DismApplyFfuImage` function just passes `null` to it.  So it doesn't look like we can get the progress.
