### ISSUE TITLE
Support for applying WIM Images

### ISSUE THREAD

**Issue by Dawid8plc** [jeffkl/ManagedDism#85]
I managed to find this repository today and I was wondering, if it would be possible to add a function that would apply a .WIM Image. I can see that there is already a function allows you to apply a .FFU image. Im sorry if there is a way to do it already and Im simply missing something, thanks in advance.

**Comment by wingers999** [comment]
You use this project to apply images - https://github.com/jeffkl/ManagedWimgApi

**Comment by Dawid8plc** [comment]
I will take a look at it, thanks!
