### ISSUE TITLE
how to correctly put  dependencyPackages , and customDataPath.

### ISSUE THREAD

**Issue by MaGrMo** [jeffkl/ManagedDism#87]
Hello i'm using  your method to add languages( LXPs) to WIM 
I Don't have a dependencyPackages  and customData.
and I've tried to put 
dependencyPackages , and customDataPath. as null,  empty list, list with one "" string, 
And I'm receiving  thrown exception: how can I correctly PUT (dependencyPackages  and customData)  attributes IF I don't have ones.  

P.S. Dism.exe add language as required) 
```
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
_DismAddProvisionedAppxPackage
   at Microsoft.Dism.DismApi.NativeMethods._DismAddProvisionedAppxPackage(DismSession session, String appPath, String[] dependencyPackages, UInt32 dependencyPackageCount, String licensePath, Boolean skipLicense, String customDataPath)
   at Microsoft.Dism.DismApi.AddProvisionedAppxPackage(DismSession session, String appPath, List`1 dependencyPackages, String licensePath, String customDataPath)
```

**Comment by jeffkl** [comment]
I'm looking into this...

**Comment by jeffkl** [comment]
@MaGrMo what version of Windows have you tried this on? Just run `ver` and paste the output here.

```
D:\>ver

Microsoft Windows [Version 10.0.18363.657]
```

It looks like this API changed in a recent release of Windows which would explain the breakage.

**Comment by jeffkl** [comment]
This should be fixed in the latest release: https://github.com/jeffkl/ManagedDism/releases/tag/v2.0.23

**Comment by MaGrMo** [comment]
Thank you Very much! I't Was impressively quick!

**Comment by jeffkl** [comment]
You're welcome, thanks for reporting the issue
