### ISSUE TITLE
request for Feature Support ESD images format

### ISSUE THREAD

**Issue by MaGrMo** [jeffkl/ManagedDism#91]
Microsoft Media Creation Tool  creates Images in ESD format
Dism.exe is supporting this format.
Is it possible to add support "esd" format for Images?
Thanks

when I adding Image in MountImage method on attribute mountPath as image in esd format i got exception:
```
An attempt was made to load a program with an incorrect format.
```

**Comment by jeffkl** [comment]
That error usually means that a 32-bit process tried to load a 64-bit assembly or visa versa.  Can you give me more details on your application and environment?

**Comment by MaGrMo** [comment]
Sure here is my OS. 
using 

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
System Type:               x64-based PC

What I do.
 I Have created   windows.Iso  image using MS MediaCreation1909  tool For Win 10.
Have copied From  ISO  sources\install.esd (think MS changed Wim to Esd  format)

And trying to Init Mount Modify (add drivers, Apptx Ubdates etc) to install.esd  using your lib.  

IF I do extract from  est image to wim image  Using Dism.exe  /export-image. Your Lib works with wim perfectly, thanks.
It would be cool to be able work with esd format directly.   (if Microsoft switched to one).

**Comment by mrherkar** [comment]
Hi guys,

I have the same problem. 

As far as I learnt after many days of research, the DISM API itself does not support (or undocumented) export image feature which we could use to export an image from an ESD file but DISM.exe does.

Only way I can manage to do this is with PowerShell Export-WindowsImage
[](url)
[https://docs.microsoft.com/en-us/powershell/module/dism/export-windowsimage?view=win10-ps](url)

You can use PowerShell in C# 

```
using System.Management.Automation; 
. . . 
            using (PowerShell ps = PowerShell.Create())
            {
                    ps.AddCommand("Export-WindowsImage");
                    ps.AddParameter("DestinationImagePath", destImagePath);
                    ps.AddParameter("SourceImagePath", sourceImagePath);
                    ps.AddParameter("SourceIndex", AnyIndexYouWantToExport);
                    ps.AddParameter("CheckIntegrity");
                    ps.AddParameter("CompressionType", "none");
                   
                    var w = ps.Invoke();
          }
. . . 
```

**Comment by jeffkl** [comment]
`Dism.exe` uses the Windows Imaging API (WIMGAPI) to export images.  I have a managed wrapper for that API as well.  https://github.com/jeffkl/ManagedWimgApi

Example code to export an image:
https://github.com/jeffkl/ManagedWimgApi/blob/999da57b08132b27e78bb4764d0978adddffdad7/src/Microsoft.Wim.Tests/ExportImageTests.cs#L22-L32

Does exporting an image work automatically if the file path ends in `.esd`?

**Comment by mrherkar** [comment]
Hi Jeff, thanks for your reply.

I tried that but I always get exception at CreateFile


![Screenshot (40)](https://user-images.githubusercontent.com/65870165/83076890-a438ea80-a076-11ea-9bdd-02e2afd54149.png)

**Comment by mrherkar** [comment]
I mean WimgApi works fine with with WIM files, but it doesn't with ESD files.

**Comment by jeffkl** [comment]
I can't find a way to mount `.esd` files but I have finally figured out how to convert a `.wim` to .`esd`.

```C#
using (WimHandle sourceWimHandle = WimgApi.CreateFile(@"D:\install.wim", WimFileAccess.Read, WimCreationDisposition.OpenExisting, WimCreateFileOptions.None, WimCompressionType.None))
{
    WimgApi.SetTemporaryPath(sourceWimHandle, @"D:\");

    using (WimHandle sourceImageHandle = WimgApi.LoadImage(sourceWimHandle, 1))
    {
        using (WimHandle destinationWimHandle = WimgApi.CreateFile(@"D:\install.esd", WimFileAccess.Write, WimCreationDisposition.CreateAlways, WimCreateFileOptions.Chunked, WimCompressionType.Lzms))
        {
            WimgApi.SetTemporaryPath(destinationWimHandle, @"D:\");

            WimgApi.ExportImage(sourceImageHandle, destinationWimHandle, WimExportImageOptions.AllowDuplicates);
        }
    }
}
```

The most important thing I found is that `dism.exe` sets the `WimCompressionType` to `Lzms` automatically for you if you specify `/Compress:recovery`.  It also sets `WimCreateFileOptions` to `Chunked` if the compression type is `Lzms`.  So you have to set these as well when using the API.

I exported an image with `dism.exe`:
```cmd
dism /Export-Image /SourceImageFile:install.wim /SourceIndex:1 /DestinationImageFile:install.esd /Compress:recovery
```
And then I exported the image with the code above to get a file that is byte-for-byte identical.

`dism.exe` can get information from the `.esd` file I exported via code:
```cmd
D:\>dism /Get-WimInfo /WimFile:D:\install.esd

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Details for image : D:\install.esd

Index : 1
Name : Windows 10 Enterprise
Description : Windows 10 Enterprise
Size : 14,356,212,795 bytes

The operation completed successfully.

D:\>dism /Get-WimInfo /WimFile:D:\install.esd /Index:1

Deployment Image Servicing and Management tool
Version: 10.0.19041.1

Details for image : D:\install.esd

Index : 1
Name : Windows 10 Enterprise
Description : Windows 10 Enterprise
Size : 14,356,212,795 bytes
WIM Bootable : No
Architecture : x64
Hal : <undefined>
Version : 10.0.17763
ServicePack Build : 1
ServicePack Level : 0
Edition : Enterprise
Installation : Client
ProductType : WinNT
ProductSuite : Terminal Server
System Root : WINDOWS
Directories : 18872
Files : 87394
Created : 9/15/2018 - 2:43:11 AM
Modified : 6/1/2020 - 4:26:21 PM
Languages :
        en-US (Default)

The operation completed successfully.
```

But `dism.exe` cannot mount the image:

```cmd
D:\>dism /Mount-Wim /WimFile:D:\install.esd /Index:1 /MountDir:D:\mount

Deployment Image Servicing and Management tool
Version: 10.0.19041.1


Error: 11

An attempt was made to load a program with an incorrect format.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log
```

The `dism.log` clearly states the problem:

```
2020-06-01 16:39:43, Warning               DISM   DISM WIM Provider: PID=31008 [ReadWimHeader:(1874) -> header version mismatch] D:\install.esd (HRESULT=0x8007000B) - CWimManager::WimProviderMsgLogCallback
[31008] [0xc144012e] 
2020-06-01 16:39:43, Error                 DISM   DISM WIM Provider: PID=31008 [WIMCreateFile:(421) -> Fail to read WIM header] D:\install.esd (HRESULT=0x8007000B) - CWimManager::WimProviderMsgLogCallback
2020-06-01 16:39:43, Error                 DISM   DISM WIM Provider: PID=31008 TID=26916 "WIM open failed." - CWimImageInfo::Mount(hr:0x8007000b)
```

Has anyone been able to successfully mount an `.esd` file with any method?

**Comment by mrherkar** [comment]
We must set compress as `/Compress:none`  at exporting otherwise we get that "nice" error at mount. 

`dism /export-image /SourceImageFile:d:\install.esd /SourceIndex:1 /DestinationImageFile:d:\install.wim /Compress:none /CheckIntegrity`

Make sure that the destination file is not exists otherwise exporting may fail (if existing wim has different compression) or dest file will be appended. 

My problem is exporting wim from an esd file. The original Microsoft provided Win10 ISO contains a boot.wim and an install.esd file. I can't make this export work via DISM API nor WimgApi, only with dism.exe and PowerShell Export-WindowsImage.

**Comment by jeffkl** [comment]
I'm able to export WIM to ESD and ESD to WIM just fine with WimgApi:

# Export WIM to ESD
```C#
using (WimHandle wimHandle = WimgApi.CreateFile(@"D:\install.wim", WimFileAccess.Read, WimCreationDisposition.OpenExisting, WimCreateFileOptions.None, WimCompressionType.None))
{
    WimgApi.SetTemporaryPath(wimHandle, @"D:\");

    using (WimHandle imageHandle = WimgApi.LoadImage(wimHandle, 1))
    {
        using (WimHandle esdHandle = WimgApi.CreateFile(@"D:\install.esd", WimFileAccess.Read | WimFileAccess.Write, WimCreationDisposition.CreateNew, WimCreateFileOptions.Chunked, WimCompressionType.Lzms))
        {
            WimgApi.SetTemporaryPath(esdHandle, @"D:\");

            WimgApi.ExportImage(imageHandle, esdHandle, WimExportImageOptions.AllowDuplicates);
        }
    }
}
```

# Export ESD to WIM
```C#
using (WimHandle esdHandle = WimgApi.CreateFile(@"D:\install.esd", WimFileAccess.Read, WimCreationDisposition.OpenExisting, WimCreateFileOptions.Chunked, WimCompressionType.Lzms))
{
    WimgApi.SetTemporaryPath(esdHandle, @"D:\");

    using (WimHandle imageHandle = WimgApi.LoadImage(esdHandle, 1))
    {
        // Export ESD to WIM
        using (WimHandle wimHandle = WimgApi.CreateFile(@"D:\install2.wim", WimFileAccess.Read | WimFileAccess.Write, WimCreationDisposition.CreateNew, WimCreateFileOptions.None, WimCompressionType.Lzx))
        {
            WimgApi.SetTemporaryPath(wimHandle, @"D:\");

            WimgApi.ExportImage(imageHandle, wimHandle, WimExportImageOptions.AllowDuplicates);
        }
    }
}
```
As long as the `WimCreateFileOptions` and `WimCompressionType` are correct, it works fine.  I am not able to mount an `.esd` file directly with any method (`dism.exe`, WimgApi).  But I can export ESD to WIM, mount it, modify it, unmount, and export back to ESD.

**Comment by mrherkar** [comment]
Awesome!

I tested ESD to WIM and it works fine! And I could implement progess callback so it's perfect for my needs.

Thank you so much

**Comment by jeffkl** [comment]
I’ll close this issue now that we have it figured out and have code samples. Thanks everyone for helping!
