### ISSUE TITLE
CBS_E_NOT_APPLICABLE error does not have friendly text

### ISSUE THREAD

**Issue by Haacker** [jeffkl/ManagedDism#92]
I am attempting to inject Windows 10 Language packs into our Windows image. I was mistakenly attempting to inject 1909 version language packs into an 1809 image and it kept failing, but not raising an exception.

If I use the DISM.EXE command line and do this, I get an Error that "the specified package is not applicable to this image". When I do this with the following code, it just seems to skip the operation and move on, without raising an exception. 

```
DismApi.Initialize(DismLogLevel.LogErrors);
                    try
                    {
                        using (DismSession session = DismApi.OpenOfflineSession(imagePath))
                        {
                            DismApi.AddPackage(
                                session: session,
                                packagePath: packagePath,
                                ignoreCheck: true,
                                preventPending: false,
                                progressCallback: HandleLTSCInjectProgress,
                                userData: null);
                        }
                    }
                    catch(DismException dm)
                    {
                        MessageBox.Show(dm.Message);
                    }
                    DismApi.Shutdown();

```
Is this something I am doing wrong, or a bug maybe?

Thanks,
Steve

**Comment by jeffkl** [comment]
Can you point me to the language pack so I can repro the issue? Thanks!

**Comment by Haacker** [comment]
Mine are downloaded from my corporate Volume License, so I cannot share them. However, if you have MSDN you can download them from there...

**Comment by wingers999** [comment]
This page has download links for Windows 10 language packs

https://gist.github.com/dexit/87f30cffa70ea6899177f536a8dc788f

**Comment by jeffkl** [comment]
The reason you're not getting an exception is because you're passing `ignoreCheck: true` which disables any errors.  This is the same as the `/IgnoreCheck` command-line argument to `dism.exe`
```cmd
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Image Version: 10.0.18363.657


/Add-Package /PackagePath:<path_to_package> [/IgnoreCheck] [/PreventPending]

  Adds one or more packages to an image. /PackagePath can point to either
  a .cab file, a .msu file, or a folder.
  Use the /IgnoreCheck switch to skip installation of the package if the
  applicability checks fail.
  Use the /PreventPending switch to skip the installation of the package if
  the package or Windows image has pending online actions.
```

However, if you pass `ignoreCheck: false`, you get an exception but the error text isn't set by DismApi.  So I'll need to hard code a check for this error so I can add the friendly text.

**Comment by Haacker** [comment]
LOL! I didn't even catch that, and I looked at it several times. Well, in any case, we both learned something from this.

Thanks!

**Comment by jeffkl** [comment]
Either way, thanks for reporting the issue.  I'll work on a fix

**Comment by jeffkl** [comment]
https://github.com/jeffkl/ManagedDism/releases/tag/v2.1.4

Will be available on NuGet.org soon
