### ISSUE TITLE
Bug: .NET 4.0 package has conflicting CallerMemberNameAttribute

### ISSUE THREAD

**Issue by aubiyko** [jeffkl/ManagedDism#99]
#96 adds publicly available `CallerMemberNameAttribute` for .NET Framework 4.0 package. But NuGet (and VS) behavior is that .NET Framework version will be installed for .NET Framework projects [(see this)](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#matching-assembly-versions-and-the-target-framework-in-a-project). That means even for .NET 4.8 .NET 4.0 will be used. It conflicts with `CallerMemberNameAttribute` from `mscorlib, Version=4.0.0.0` and, thus, not even builds.

**Comment by jeffkl** [comment]
Thanks for reporting this, I'll work on a fix.
